---
title: "Stadtökonomie"
bibliography: references.bib
number-sections: true
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

# Einleitung

Afrika ist einer der Regionen, die global gesehen vor den größten Herausforderungen im 21. Jahrhundert stehen. Bis 2050 wird die derzeitige Bevölkerung von 1.1 Milliarden Menschen auf das Doppelte anwachsen, wobei 80% dieses Wachstums in Städten stattfinden wird. Diese zusätzlichen Stadtbewohner treffen jedoch auf geringe Beschäftigungsmöglichkeiten und wenig wirtschaftlichen Aufschwung, gepaart mit einer zunehmenden Bedrohung durch den Klimawandel. Die Implikationen, die sich daraus für politische, ökonomische und gesellschaftliche Handlungen ergeben, sind zahlreich, und ein großer Teil hängt von der Möglichkeit ab, die Urbanisierung in wohlstandssteigernde Bahnen zu lenken.

Mit diesen Themen beschäftigen sich Vernon Henderson, Adam Storeygard und Uwe Deichmann in ihrer wissenschaftlichen Arbeit mit dem Titel "Has climate change driven urbanization in Africa?". Der Artikel wurde 2016 im renommierten Journal of Development Economics veröffentlicht und untersucht die Zusammenhänge zwischen Urbanisierung und Klimawandel in Subsahara-Afrika (vgl. @hendersonHasClimateChange2017 )

Die beiden Fragen, die die Autoren zu beantworten versuchen, sind einerseits, ob ungünstige Klimaveränderungen dazu führen, dass die Menschen aus den ländlichen Gebieten in die Städte ziehen und andererseits, ob dieser Zuzug dass Gesamteinkommen der Städte erhöht. Die Motivation hinter der Fragestellung ist also, ob die Urbanisierung in Afrika ein Ausweg aus den sich verändernden klimatischen Bedigungen sein kann

## Hintergrund

Die Frage, was das Stadtwachstum antreibt, wird in der stadtökonomischen Forschung weit diskutiert. Unterschieden wird dabei im Wesentlichen zwischen Pull-Faktoren wie bspw. Wirtschaftliche Aussichten und Push-Faktoren wie beispielsweise Konflikte. 

Zur Frage des Klimawandels als Push-Faktor der Urbanisierung, die die Autoren untersuchen, ist die nächstverwandte Arbeit von @barriosClimaticChangeRural2006a . Sie untersuchten die Fragestellung anhand eines Paneldatensatzes von 36 Ländern aus Subsahara-Afrika und verglichen ihre Ergebnisse mit Entwicklungsländern aus anderen Regionen. Änhlich geht @brucknerEconomicGrowthSize2012 vor, der den Zusammenhang zwischen dem Anteil der Landwirtschaft am BIP und Niederschlag untersucht. Auch @hendersonUrbanizationSubSaharanAfrica2013 untersuchten diese Frage bereits für die Weltbank

Die Autoren des aktuellen Papers erweitern diese Forschung, indem sie zwei Probleme angehen, die die genannten Arbeiten nicht addressieren konnten. Einerseits die beträchtliche inländische Heterogenität durch die Konstruktion eines regionalen und subnationalen Datensatzes. Andererseits die auf Interpolation beruhenden Bevölkerungsdaten durch Nutzen der originalen Zensusdaten. Wir gehen auf diese Daten näher Absatz 2.1 in ein.

Ein weiteres Alleinstellungsmerkmal der Forschungsarbeit ist, dass die Autoren den Einfluss des Klimawandels auf Urbanisierung und Einkommensveränderungen ausdifferenzieren nach dem Industrialisierungsgrad der Stadt. Dieser Ansatz wurde so in noch keinem Artikel verfolgt.

-   Zu Effekt von Klimawandel auf Afrika

    -   Afrika diverses Klima

-   Effekt von klimawandel auf Landwirtschaft

-   

# Vorgehensweise

Aufgrund der unterschiedlichen Datensätze werden wir die Vorgehensweise im Folgenden für beide Forschungsfragen getrennt voneinander betrachten. Anschließend gehen wir noch kurz auf das mathematische Modell ein.

## Klimaveränderung und Urbanisierung

## Klimaveränderung und Einkommenssteigerung

## Mathematisches Modell

# Diskussion

## Bewertung

-   Paper stellt erweitert den Forschungstand auf jedenfall

-   hochrelevant für aktuelle Zeit

-   leider Verbindung beider Fragen nicht so gut geklappt, aufgrund komplett unterschiedlicher Daten und Zeiträume

-   sehr interessante Quelle für Stand der Industrialisierung

    -   leider etwas veraltet, es hat sich seit den 60ern dann doch etwas getan
    -   betont auch in Einleitung, dass es ein Tip eines guten Kollegen war

## Schlussfolgerungen

-   Afrika wird von Klimawandel hart getroffen

-   bereits jetzt nur marginal geeignet für landwirtschaftliche Produktion

-   industrialisierte Distrikte können Klimawandelfolgen entgehen

    -   Jedoch: Afrika wenig strukturelle Transformation
    -   und einhergehend mit intensiver Industrie ist Verschmutzung, die damit nicht übersprungen werden kann (Leapfrogging)

-   Folgen für landwirtschaftliche Produktion können mithilfe von verstärkter Adaption von Dünger und Bewässerung aufgefangen werden

    -   sehr geringe Verbreitung und quasi kein Wachstum seit 80ern

## Forschungsansatz

# Appendix

## Literaturverzeichnis
